# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portions', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('cooking_type', models.CharField(max_length=255)),
                ('recipe', models.TextField()),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='DishCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dish_country',
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=250)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiefparser.Dish')),
            ],
            options={
                'db_table': 'dish_ingredient',
            },
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'dish_type',
            },
        ),
        migrations.CreateModel(
            name='EnergyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorific', models.CharField(max_length=150, null=True)),
                ('proteins', models.CharField(max_length=150, null=True)),
                ('fats', models.CharField(max_length=150, null=True)),
                ('carbohydrates', models.CharField(max_length=150, null=True)),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'db_table': 'energy_value',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiefparser.Ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiefparser.DishCountry'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiefparser.DishType'),
        ),
        migrations.AddField(
            model_name='dish',
            name='energy_val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiefparser.EnergyValue'),
        ),
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiefparser.Rating'),
        ),
    ]
