# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiefparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
