# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiefparser', '0002_auto_20160319_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='cooking_type',
            new_name='cooking_time',
        ),
    ]
