# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiefparser', '0004_auto_20160320_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='uid',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
