# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chiefparser', '0005_dish_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chiefparser.DishCountry'),
        ),
    ]
