# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiefparser', '0007_auto_20160323_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='logo_cdn_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='logo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dishcountry',
            name='logo_cdn_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dishcountry',
            name='logo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='logo_cdn_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='logo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='reps',
            field=models.IntegerField(null=True),
        ),
    ]
