# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiefparser', '0008_auto_20160325_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='reps',
        ),
    ]
