# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20160527_2159'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proxy',
            table='ProxyTable',
        ),
    ]
